# Generated by Django 6.0 on 2026-01-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_token_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_version',
        ),
        migrations.AddField(
            model_name='user',
            name='is_token_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
