# Generated by Django 6.0 on 2026-01-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_token_version_user_is_token_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_token_revoked',
        ),
    ]
